### PR TITLE
Merge upstream 2.17.0 release

### PR DESCRIPTION
**Pull request by wohali**
Not only are we a few revisions (years!) behind, but fixes have landed upstream for situations that may cause handlers to block forever, see 61a65fea7d6b1e9f93c4a2c6b96e96dee02bec6e and apache/couchdb#1117 and apache/couchdb#1063 for example.

Paging @rnewson.

Once this lands I will re-tag and we can bump `rebar.config.script` in `apache/couchdb`.

### CODE REVIEW

**Comment by wohali** [comment]
I can't sort out what is wrong with Travis here, by the way. I get the same errors when running `rebar3 eunit` and cloning `mochi/mochiweb`. *shrug*

**Comment by janl** [comment]
mochiweb master comes with its own `./rebar` script that is run on travis. This branch doesn’t seem to have it. I’ve pushed a commit with that file onto this branch. We can mack it out if this doesn’t help

**Comment by janl** [comment]
works, woot.

**Comment by rnewson** [comment]
looking now. the diff between this and v2.17.0 is zero, so that's good. I think it would be neat if we could point to the (signed) v2.17.0 tag itself. figuring out the git mechanics atm.

**Comment by janl** [comment]
@rnewson figured it out, we already had all the commits and were missing the tag, so that’s pushed now.

**Comment by rnewson** [comment]
yeah, my bad. dropped the ball on the last few steps six months ago.

**Comment by janl** [comment]
PR here: https://github.com/apache/couchdb/pull/1173

**Comment by wohali** [comment]
I'm going to merge this just so master and upstream look identical.

**Pull request merged**
